name: Maven Build

on:
  push:
    branches: [ main, 1.3.x ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:

    - name: Check out sources
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'

    - name: Build with Maven
      run: ./mvnw -B

  integrations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        boot-version: ["2.5.14", "2.7.5", "3.0.0-SNAPSHOT"]
    name: Integration test (Boot ${{ matrix.boot-version }})
    needs: build
    steps:

    - name: Check out sources
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'

    - name: Build with Maven (Boot ${{ matrix.boot-version }})
      run: sed -i -e 's/2.6.13/${{ matrix.boot-version }}/g' ./pom.xml && ./mvnw dependency:list -B && ./mvnw -B

